-- =============================================================================
-- FILE:        data/seed_data.sql
-- Description: Reference seed data — cities, zones, promotions.
--              This file is also auto-generated by data/generate_data.py.
--              Run this BEFORE loading order/customer data.
-- =============================================================================

BEGIN;

-- Cities
INSERT INTO cities(city_id,city_name,state,country,timezone) VALUES
(1,'Mumbai','Maharashtra','India','Asia/Kolkata'),
(2,'Delhi','Delhi','India','Asia/Kolkata'),
(3,'Bangalore','Karnataka','India','Asia/Kolkata'),
(4,'Hyderabad','Telangana','India','Asia/Kolkata'),
(5,'Chennai','Tamil Nadu','India','Asia/Kolkata'),
(6,'Pune','Maharashtra','India','Asia/Kolkata'),
(7,'Kolkata','West Bengal','India','Asia/Kolkata'),
(8,'Ahmedabad','Gujarat','India','Asia/Kolkata'),
(9,'Jaipur','Rajasthan','India','Asia/Kolkata'),
(10,'Lucknow','Uttar Pradesh','India','Asia/Kolkata')
ON CONFLICT DO NOTHING;

SELECT setval('cities_city_id_seq', 10);

-- Zones (10 per city = 100 zones)
INSERT INTO zones(zone_id,city_id,zone_name,avg_delivery_time_mins) VALUES
-- Mumbai Zones
(1,1,'Mumbai Zone 1 - Andheri',28),(2,1,'Mumbai Zone 2 - Bandra',25),
(3,1,'Mumbai Zone 3 - Dadar',30),(4,1,'Mumbai Zone 4 - Juhu',27),
(5,1,'Mumbai Zone 5 - Worli',22),(6,1,'Mumbai Zone 6 - Kurla',32),
(7,1,'Mumbai Zone 7 - Thane',38),(8,1,'Mumbai Zone 8 - Borivali',35),
(9,1,'Mumbai Zone 9 - Navi Mumbai',40),(10,1,'Mumbai Zone 10 - Powai',26),
-- Delhi Zones
(11,2,'Delhi Zone 1 - Connaught Place',24),(12,2,'Delhi Zone 2 - Lajpat Nagar',28),
(13,2,'Delhi Zone 3 - Hauz Khas',26),(14,2,'Delhi Zone 4 - Noida',35),
(15,2,'Delhi Zone 5 - Gurgaon',38),(16,2,'Delhi Zone 6 - Dwarka',33),
(17,2,'Delhi Zone 7 - Saket',27),(18,2,'Delhi Zone 8 - Janakpuri',30),
(19,2,'Delhi Zone 9 - Rohini',32),(20,2,'Delhi Zone 10 - Vasant Kunj',29),
-- Bangalore Zones
(21,3,'Bangalore Zone 1 - Koramangala',22),(22,3,'Bangalore Zone 2 - Indiranagar',24),
(23,3,'Bangalore Zone 3 - HSR Layout',26),(24,3,'Bangalore Zone 4 - Whitefield',40),
(25,3,'Bangalore Zone 5 - Jayanagar',28),(26,3,'Bangalore Zone 6 - Electronic City',42),
(27,3,'Bangalore Zone 7 - Marathahalli',35),(28,3,'Bangalore Zone 8 - BTM Layout',27),
(29,3,'Bangalore Zone 9 - Malleshwaram',30),(30,3,'Bangalore Zone 10 - Yelahanka',38)
ON CONFLICT DO NOTHING;

-- Fill remaining cities with generic zones
DO $$
DECLARE
    cid INT; z INT; zid INT;
BEGIN
    FOR cid IN 4..10 LOOP
        FOR z IN 1..10 LOOP
            zid := (cid - 1) * 10 + z;
            INSERT INTO zones(zone_id, city_id, zone_name, avg_delivery_time_mins)
            VALUES (zid, cid,
                    (SELECT city_name FROM cities WHERE city_id = cid) || ' Zone ' || z,
                    20 + (z * 2))
            ON CONFLICT DO NOTHING;
        END LOOP;
    END LOOP;
END $$;

SELECT setval('zones_zone_id_seq', 100);

-- Promotions
INSERT INTO promotions(promo_code,promo_name,promo_type,discount_value,
    min_order_amount,max_discount,max_uses,start_date,end_date,is_active,applicable_to) VALUES
('WELCOME50','New User Welcome','FLAT',50,149,50,NULL,'2021-01-01','2026-12-31',TRUE,'NEW_USER'),
('SAVE20','Save 20%','PERCENT',20,199,80,100000,'2021-01-01','2026-12-31',TRUE,'ALL'),
('FREEDEL','Free Delivery','FREE_DELIVERY',40,99,40,NULL,'2021-01-01','2026-12-31',TRUE,'ALL'),
('WEEKEND30','Weekend Special 30%','PERCENT',30,249,120,50000,'2021-01-01','2026-12-31',TRUE,'ALL'),
('LOYAL100','Loyalty Reward ₹100','FLAT',100,399,100,NULL,'2022-01-01','2026-12-31',TRUE,'EXISTING'),
('FLASH40','Flash Sale 40%','PERCENT',40,299,150,10000,'2023-01-01','2023-12-31',FALSE,'ALL'),
('DINNER25','Dinner Rush 25%','PERCENT',25,199,100,75000,'2022-01-01','2026-12-31',TRUE,'ALL'),
('NEWREST50','New Restaurant ₹50','FLAT',50,149,50,NULL,'2023-01-01','2026-12-31',TRUE,'ALL'),
('MONSOON20','Monsoon Special','PERCENT',20,199,80,30000,'2023-06-01','2023-09-30',FALSE,'ALL'),
('FESTIVE100','Festival Bonus','FLAT',100,499,100,25000,'2023-10-01','2023-11-30',FALSE,'ALL')
ON CONFLICT DO NOTHING;

COMMIT;

SELECT 'cities' AS entity, COUNT(*) AS rows FROM cities
UNION ALL SELECT 'zones', COUNT(*) FROM zones
UNION ALL SELECT 'promotions', COUNT(*) FROM promotions;
